### ISSUE TITLE
Atlasloot not showing up on the Minimap Button Frame

### ISSUE THREAD

**Issue by IsjaslawEisenstadt** [ElvUI-TBC/ElvUI_MinimapButtons#1]
The icon from the addon atlasloot isn't showing up on the minimap and the minimap button frame.
This could also be a bug related to ElvUi itself since it doesn't show up when turning off this addon either.

**Comment by Jovzin** [comment]
Hello, I must say I have the same issue. 
Do not see Atlasloot enchanced button but well I do no see the minimap button frame at all.
