### ISSUE TITLE
Minimap buttons frame not showing at all.

### ISSUE THREAD

**Issue by Jovzin** [ElvUI-TBC/ElvUI_MinimapButtons#3]
Hello I have an issue with this addon.
When I enable it I do not see it at all. 
Was trying to put there Atlasloot enchanced minimap button but nothing. Bigwigs button is not showing too.

**Comment by Fanquar** [comment]
remove the FuBar2Broker folder in the ElvUI\libs folder and try again
(back it up or whatnot, just move it out of there)
